### ISSUE TITLE
Invalid server response

### ISSUE THREAD

**Issue by cahukS** [spamwax/alfred-pinboard-rs#1]
When I enter my Pinboard credentials, I get a notification that the credentials are successfully set but after a few seconds I get a new notification about invalid server response (invalid port number....; I can't see the entire log message; [here](https://www.dropbox.com/s/1e8wg5h8du1llzw/Screenshot%202018-03-31%2012.33.17.png?dl=0) is a screenshot on Dropbox).

**Comment by cahukS** [comment]
I get this after running ./alfred-pinboard-rs update:

{"items":[{"icon":{"path":"erroricon.icns"},"subtitle":"invalid server response: invalid port number at line 3353 column 57","title":"Error"}]}⏎

**Comment by spamwax** [comment]
ok, run this to see if you can actually talk to Pinboard server without using this workflow:

```
curl https://api.pinboard.in/v1/posts/all\?auth_token\=your_username:api_token > pins.xml
```

`pins.xml` should then contain all your bookmarks.

**Comment by cahukS** [comment]
The curl command works, downloaded my bookmarks.

**Comment by spamwax** [comment]
ok, I am guessing that there is a text encoding issue related to one of the bookmarks you have based on the "line 3353 column 57".
However I am not sure why it's talking about "invalid port number"
To better debug, I may need to introduce more verbose logging to code but for now, you can run this and I'll try to see where the error is happening based on what output you get:

```
RUST_LOG=rusty_pin=debug,alfred_pinboard_rs=debug ./alfred-pinboard-rs update
```
By the way, does your Pinboard user name have any non-ASCII character?

**Comment by cahukS** [comment]
`DEBUG 2018-04-01T08:47:18Z: alfred_pinboard_rs: Parsing input arguments.
DEBUG 2018-04-01T08:47:18Z: alfred_pinboard_rs: Deciding on which command branch
DEBUG 2018-04-01T08:47:18Z: alfred_pinboard_rs: Starting in setup
DEBUG 2018-04-01T08:47:18Z: alfred_pinboard_rs::workflow_config: Starting in setup
DEBUG 2018-04-01T08:47:18Z: alfred_pinboard_rs::workflow_config: Starting in get_workflow_dirs
DEBUG 2018-04-01T08:47:18Z: alfred_pinboard_rs::workflow_config: Starting in read
DEBUG 2018-04-01T08:47:18Z: alfred_pinboard_rs::workflow_config: Starting in get_alfred_version
DEBUG 2018-04-01T08:47:18Z: rusty_pin::pinboard: pinb::new: calling CachedData::new
DEBUG 2018-04-01T08:47:18Z: rusty_pin::pinboard::cached_data: new: starting
DEBUG 2018-04-01T08:47:18Z: rusty_pin::pinboard::cached_data: create_cache_dir: starting
DEBUG 2018-04-01T08:47:18Z: rusty_pin::pinboard::cached_data: load_cache_data_from_file: starting
DEBUG 2018-04-01T08:47:18Z: rusty_pin::pinboard::cached_data: cache_ok: starting
DEBUG 2018-04-01T08:47:18Z: rusty_pin::pinboard: pinb::new: cache file missing, calling update
DEBUG 2018-04-01T08:47:18Z: rusty_pin::pinboard::cached_data: update_cache: starting
DEBUG 2018-04-01T08:47:18Z: rusty_pin::pinboard::api: all_pins: starting.
DEBUG 2018-04-01T08:47:18Z: rusty_pin::pinboard::api: get_api_response: starting.
DEBUG 2018-04-01T08:47:18Z: rusty_pin::pinboard::api: add_auth_token: starting.
DEBUG 2018-04-01T08:47:39Z: alfred_pinboard_rs: Starting in show_error_alfred
{"items":[{"icon":{"path":"erroricon.icns"},"subtitle":"invalid server response: invalid port number at line 3353 column 57","title":"Error"}]}`

No non-ASCII character in my username.

**Comment by spamwax** [comment]
when you do `./alfred-pinboard-rs config -a your_username:api_token`
the last part should look like this: `cahukS:3622E6` , i.e. user name followed by a colon `:` and then api token with hex number

**Comment by cahukS** [comment]
Yes, I'm doing it that way.

**Comment by spamwax** [comment]
According to the log you posted, problem happens when adding your authorization token to the url we send to Pinboard. Maybe when you were using Alfred to setup up this workflow using `pa` command something went wrong.

Check the `settings.json` file in `~/Library/Application Support/Alfred 3/Workflow Data/cc.hamid.alfred-pinboard-rs` folder. There should be a key in that file named `auth_token`. Check its value, it should be `username:token` with no spaces and no-ascii characters.
Mines looks like this: "auth_token":"spamwax:AEBBBFBB3BB0BBBBB"

If that looks okay and you still get the same error message, you can then fully delete these two folders and try setting up the workflow again by using `pa username:token` in Alfred's window.
`~/Library/Application Support/Alfred 3/Workflow Data/cc.hamid.alfred-pinboard-rs`
`~/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/cc.hamid.alfred-pinboard-rs`

**Comment by cahukS** [comment]
Ok, I deleted the two folders and ran the update command without setting the auth token. I got the same error - invalid port number. Is this strange?

**Comment by spamwax** [comment]
after you delete the folders you need to do one-time setup of the workflow.
Trigger Alfred window, and in its window type `pa ` followed by your `username:token`
make sure there are no spaces after the token, something like this in Alfred's window:
`pa cahukS:0123456789ABCDEF`

**Comment by cahukS** [comment]
What I want to say is that even if I set the token the error is the same. Perhaps Alfred doesn't read the settings JSON?

**Comment by spamwax** [comment]
I'd guess it is reading it but somehow your settings file is not following the required format.

Download this [alfred-pinboard-rs](https://www.dropbox.com/s/wo7kgy8mnaovdym/alfred-pinboard-rs?dl=1) and copy it in the workflow's folder. Then run this and see if the token that is printed in the log matches what you entered when setting up the Workflow:
```
RUST_LOG=rusty_pin=debug,alfred_pinboard_rs=debug ./alfred-pinboard-rs update
```

**Comment by cahukS** [comment]
What is the path for the workflow?

**Comment by spamwax** [comment]
actually you don't need to copy it to workflow's path. If it is in `~/Download`, you can do this:

```
cd ~/Downloads
chmod u+x alfred-pinboard-rs
./alfred-pinboard-rs config -a your_username:api_token
RUST_LOG=rusty_pin=debug,alfred_pinboard_rs=debug ./alfred-pinboard-rs update
```

On my machine, the path for workflow is:
`~/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.665EAB20-5141-463D-8C5A-90093EEAA756`

**Comment by cahukS** [comment]
I think there is a progress.

`DEBUG 2018-04-01T21:13:30Z: rusty_pin::pinboard: pinb::new: calling CachedData::new
DEBUG 2018-04-01T21:13:30Z: rusty_pin::pinboard::cached_data: new: starting
DEBUG 2018-04-01T21:13:30Z: rusty_pin::pinboard::cached_data: create_cache_dir: starting
DEBUG 2018-04-01T21:13:30Z: rusty_pin::pinboard::cached_data: load_cache_data_from_file: starting
DEBUG 2018-04-01T21:13:30Z: rusty_pin::pinboard::cached_data: cache_ok: starting
DEBUG 2018-04-01T21:13:30Z: rusty_pin::pinboard: pinb::new: cache file missing, calling update
DEBUG 2018-04-01T21:13:30Z: rusty_pin::pinboard::cached_data: update_cache: starting
DEBUG 2018-04-01T21:13:30Z: rusty_pin::pinboard::api: all_pins: starting.
DEBUG 2018-04-01T21:13:30Z: rusty_pin::pinboard::api: get_api_response: starting.
DEBUG 2018-04-01T21:13:30Z: rusty_pin::pinboard::api: add_auth_token: starting.
DEBUG 2018-04-01T21:13:30Z: rusty_pin::pinboard::api:   token: `username:token`
DEBUG 2018-04-01T21:13:30Z: rusty_pin::pinboard::api:  url: "https://api.pinboard.in/v1/posts/all?format=json&auth_token=username%3token"
{"items":[{"icon":{"path":"erroricon.icns"},"subtitle":"invalid server response: invalid port number at line 3353 column 57","title":"Error"}]}⏎`

As you see there now two new lines after `add_auth_token: starting`

**Comment by spamwax** [comment]
:)
It seems you are not using your actual user name and token from Pinboard.
Go to [your settings page on Pinboard](https://pinboard.in/settings/password) to retrieve your authentication token and exactly use that in Alfred's window to set up this workflow.
Seems you missed [installation instructions](https://github.com/spamwax/alfred-pinboard-rs#installation--setup) on front page.

**Comment by spamwax** [comment]
or if I am mistaking and you modified the log before posting, then I have to work on more logging

**Comment by cahukS** [comment]
I modified the log before posting.

**Comment by spamwax** [comment]
ok, let's see what we get from this [new binary](https://www.dropbox.com/s/wo7kgy8mnaovdym/alfred-pinboard-rs?dl=0). After downloading it do the same thing as above:

```
cd ~/Downloads
chmod u+x alfred-pinboard-rs
./alfred-pinboard-rs config -a your_username:api_token
RUST_LOG=rusty_pin=debug,alfred_pinboard_rs=debug ./alfred-pinboard-rs update
```

Post the output here.
If you get the same error message, then run this:

```
 curl https://api.pinboard.in/v1/posts/all\?format\=json\&auth_token\=your_username:api_token > bookmarks.json
```
(don't forget to replace username/token in above with yours)

 Goto to line 3353 of `bookmarks.json`, and if you don't mind share that line and couple of its surroundings with me. If you don't wanna share those particular bookmarks, then delete them from your Pinboard account on their website (after backing up) and see running an update would get it fixed or not.

**Comment by cahukS** [comment]
Ok, everything is fixed now. I had a few bookmarks with wrong URL syntax. Deleted those bookmarks from Pinboard and now Alfred shows the bookmarks. Thank you very much for your help.

**Comment by spamwax** [comment]
great!
