### ISSUE TITLE
Support Opera

### ISSUE THREAD

**Issue by ebouchut** [spamwax/alfred-pinboard-rs#10]
Hi, 

First off, thank you for this great workflow.
I tried to bookmark a page in Opera and got this error `Cannot get browser's URL`.
FYI, I have both Chrome and Opera opened at the same time, but opera is the frontmost window when trying to bookmark the current page.

Of course, I noticed while reading the README that Opera is not a supported browser.

Do you plan on supporting it in the future?

Thanks,

**Comment by spamwax** [comment]
please upgrade to latest version and report back here.

**Comment by ebouchut** [comment]
Thank you.
v0.14.2  works fine :+1:.
