### ISSUE TITLE
Support showing the bookmarks quickly filter as like unread, started

### ISSUE THREAD

**Issue by xiajinchun** [spamwax/alfred-pinboard-rs#11]
That's a great ponboard workflow for alfred and very nice feature for searching and updating bookmarks.
But I have a requirement, that's showing the bookmarks quickly filter as like unread, started, private and public. 
Because I usually save bookmark as a read lately, so the reading list of unread is usefully.
Would you guys please support this feature? 
Thanks.

**Comment by spamwax** [comment]
this is not possible since Pinboard api doesn't provide such information.
