### ISSUE TITLE
Semicolon for short description is not working

### ISSUE THREAD

**Issue by Nikscorp** [spamwax/alfred-pinboard-rs#12]
**Problem**

Workflow is not parsing semicolon correct to add a short description to new bookmark.

**Actual**

<img width="577" alt="screen shot 2018-08-27 at 01 26 51" src="https://user-images.githubusercontent.com/18235332/44633815-a7321300-a998-11e8-8451-74942b83cd4f.png">
<img width="578" alt="screen shot 2018-08-27 at 01 27 01" src="https://user-images.githubusercontent.com/18235332/44633816-a7321300-a998-11e8-9730-b613aebaf31a.png">
<img width="580" alt="screen shot 2018-08-27 at 01 29 55" src="https://user-images.githubusercontent.com/18235332/44633819-bc0ea680-a998-11e8-99e5-5ee9a11424ef.png">

**Expected**

As described in README.md

![Expected](https://raw.githubusercontent.com/spamwax/alfred-pinboard-rs/master/res/images/adding-notes.png)

**Environment**

Alfred  - `3.6.2 Build 922, Wednesday 11th July 2018`
Workflow - `0.14.0`

**Comment by spamwax** [comment]
Thanks for reporting. Please use the update feature of the workflow to install the latest version.

If it's not fixed, please post back.

**Comment by Nikscorp** [comment]
`0.14.2` works for me. Thank you for a quick fix!
