### ISSUE TITLE
Extra step needed for installation

### ISSUE THREAD

**Issue by will-henney** [spamwax/alfred-pinboard-rs#120]
Thanks so much for this workflow - it works great.  I just noted a small hiccup in the installation process that perhaps should be documented.  The first time I ran it to set my API key, it failed with the error:

`“alfred-pinboard-rs” cannot be opened because the developer cannot be verified.`

To fix this, I had to open the workflow's folder in Finder and explicitly run the `alfred-pinboard-rs` executable once via "Open" from the context menu, which gave me the option of authorizing the app.  After that, everything has worked flawlessly.

Cheers

Will

**Comment by spamwax** [comment]
Thanks for the report and workaround. Which version of macOS you are using?
My hardware doesn't support the latest version of macOS so I cannot fully test these type of rough edges.

**Comment by will-henney** [comment]
I was on Catalina. I have now updated to Big Sur, which I imagine would be similar. 

With respect to the original problem, I am not sure there is anything you can do about it short of signing your binary with an Apple developer ID, which requires paying 100 USD a year :(

I found an alternative workaround for the end-user in [this forum post](https://www.alfredforum.com/topic/13824-workflow-fail-with-developer-cannot-be-verified-errors-in-catalina/?do=findComment&comment=72101), but I am not sure that it is any simpler than my method.

**Comment by spamwax** [comment]
Thanks, added your links to readme.md
