### ISSUE TITLE
Error in Alfred 5 Early Access

### ISSUE THREAD

**Issue by gingerbeardman** [spamwax/alfred-pinboard-rs#141]
I'm getting the following error in [Rusty Pin](https://github.com/spamwax/alfred-pinboard-rs/releases/tag/0.16.7) pinboard workflow, in Alfred 5 Early Access.
 
Obviously the XML is wrong, but it somehow passes as OK in Alfred 4.

```xml
[09:49:08.193] WARNING: Rusty Pin[Script Filter] XML Parse Error 'The operation couldn’t be completed. (NSXMLParserErrorDomain error 65.)'. Row 7, Col 24: 'attributes construct error' in XML:
<?xml version="1.0" encoding="UTF-8"?>
<items>
    <item arg="tax" autocomplete="tax">
        <title>tax</title>
        <subtitle>NEW TAG</subtitle>
        <icon>tag.png</icon>
        <mod key="ctrl"<mod subtitle="Mark the bookmark as TOREAD."/>
        <mod key="alt"<mod subtitle="Post the bookmark as private."/>
    </item>
    <item arg="syntax" autocomplete="syntax">
        <title>syntax</title>
        <subtitle>4</subtitle>
        <icon>tag.png</icon>
        <mod key="alt"<mod subtitle="Post the bookmark as private."/>
        <mod key="ctrl"<mod subtitle="Mark the bookmark as TOREAD."/>
    </item>
</items>
```

**Comment by spamwax** [comment]
I will get the early access next week after the holidays here and work on this.
Thanks for reporting.

**Comment by gingerbeardman** [comment]
the XML from the Alfred debug log.

**Comment by spamwax** [comment]
If you can please unzip the [attached file](https://www.dropbox.com/s/xozi61cuxl6h5a9/alfred-debug.zip?dl=1) and replace the 'alfred-pinboard-rs' file in workflow's directory with it.
Then in Alfred, run `pconf` and look for something like below in Alfred's debug window:

`[2022-06-30T20:16:17Z DEBUG alfred_pinboard_rs::commands::config] Config { alfred_version: Version { major: 4, minor: 6, patch: 7 },`

The version shown there should match with your current/active Alfred instance.

You can also use this [simple workflow](https://www.dropbox.com/s/t90o6xmxuegijwh/showalfred_version.alfredworkflow?dl=1) to show the current version of alfred that it stores in `alfred_version` env. variable

**Comment by gingerbeardman** [comment]
> If you can please unzip the attached file

Sadly I am on an Apple silicon ARM machine, and I have not installed the Rosetta 2 needed to run Intel binaries. The existing version of Rusty Pin features a Universal build supporting both x64 and arm64.

> You can also use this simple workflow

5.0 EA5

![Screen shot 2022-07-01 at 12 05 38](https://user-images.githubusercontent.com/49612/176882944-a7fa920c-8bb1-4138-acdd-cf00de0998f2.png)

**Comment by nickokgo** [comment]
Hey @spamwax did you getting it working yet? I'm having the same issue using Alfred 5

**Comment by spamwax** [comment]
As I guessed, the early access is reporting "non-valid" versions for Alfred hence breaking the logic of this workflow.
I will try to do a more complete test of the early access before releasing a new update as I am hesitant to release a new update for small number of users while Alfred 5.0 is not officially released.
However if testing proves to be longer than a day or two, I will update the workflow before Alfred 5.0 is accessible to everyone.

**Comment by gingerbeardman** [comment]
Thanks for the updated workflow!
