### ISSUE TITLE
pconf settings keeps reverting

### ISSUE THREAD

**Issue by mdi** [spamwax/alfred-pinboard-rs#16]
Using `pconf`, I keep having to reset "Mark new bookmarks as toread" back to `false`. It seems the config changes don't stick.

**Comment by mdi** [comment]
Actually, it appears none of the settings in `pconf` are sticking when changed.

**Comment by spamwax** [comment]
ok, I will test this when I get home. can you go to the setting directory of the plugin and report its last modified timestamp

**Comment by spamwax** [comment]
the directory is `~/Library/Application Support/Alfred 3/Workflow Data/cc.hamid.alfred-pinboard-rs` and you should see a file called `settings.json` there

**Comment by mdi** [comment]
Closing as this seems to no longer be happening. Very strange.
