### ISSUE TITLE
As a user I would like to be able to open the pinned link without the title case being converted

### ISSUE THREAD

**Issue by atmawarin** [spamwax/alfred-pinboard-rs#19]
Hi spamwax, 

Just found that the extension convert the title case. So instead of open this link : 
https://docs.google.com/spreadsheets/d/1WRO40bescpob6kjvey3qhyihfggxxiuqzynyrl8fj9m

It open this link 
https://docs.google.com/spreadsheets/d/1wrm40bescpob6kjvey3qhyihfggxxiuqzynyrl8fj9m

While this is work for 90% site out there. Google seems treat the title case as important. As such when I open that link in google drive, it failed to open. 

Is it possible to keep the title case intact? Thanks.

**Comment by spamwax** [comment]
I think I understand what you are referring to, I'll push an update soon.

**Comment by atmawarin** [comment]
Thanks! Looking forward to it :).
