### ISSUE TITLE
Can't load bookmarks: deserialization error

### ISSUE THREAD

**Issue by jberkel** [spamwax/alfred-pinboard-rs#2]
v0.10.10

```sh
$ ./alfred-pinboard-rs config -a [...]
$ ./alfred-pinboard-rs update
{"items":[{"icon":{"path":"erroricon.icns"},"subtitle":"serde error: invalid type: boolean `false`, expected a string at line 1964 column 60","title":"Error"}]}[
```

posts/all, line 1964:
```json
 {"href":"http:\/\/www.dialektkarte.de\/","description":false,"extended":"German dialects. Click on a pin on the  map and hear speaker from that part of Germany","meta":"04cb556fa05daff3fb210eb2906d46c3","hash":"8fe8b63d7fcf5428385bfe0031f1bb33","time":"2016-01-29T16:29:05Z","shared":"yes","toread":"no","tags":""},
```

There was only one bookmark with a `false` description. Looking at the API docs the type is string, so it must be a type anomaly on the server. I deleted it and got the next error:

```json
{"items":[{"icon":{"path":"erroricon.icns"},"subtitle":"serde error: relative URL without a base at line 5634 column 12","title":"Error"}]}
```

```
{"href":"\/","description":"","extended":"","meta":"a72a1627a6211c18fcc90f4aefd9b842","hash":"6666cd76f96956469e7be39d750cc7d9","time":"1970-01-01T00:00:00Z","shared":"yes","toread":"no","tags":""}]
```

Unfortunately I can't delete this one bad entry (and it doesn't show in the web interface):

```sh
$ curl -v 'https://api.pinboard.in/v1/posts/delete?format=json&auth_token=[...]&url=%2F'
{"result_code":"item not found"}
```

**Comment by spamwax** [comment]
Thanks for the report, appreciated.
I'll look into this soon

**Comment by jberkel** [comment]
```
 INFO 2018-04-14T05:28:16Z: rusty_pin::pinboard::api: couldn't parse 1 bookmarks
```

it works now, thanks!

unrelated, but I'd be interested to hear your opinion on rust vs go, since you reimplemented the whole project (I used the go version previously)

**Comment by spamwax** [comment]
Thanks for testing.

Learning from go version obviously made this codebase better but in general

- lack of generics in go made even a simple sorting unpleasant.
- not that it matters a lot for this project, but rust version runs faster in my benchmarks
- rust forced me to handle errors properly and think about a plan in advance
- go was faster to prototype and develop.
- go co-routines & channels seemed pretty good to me in terms of learning and ease of implementing.
- i really like iterators and how it forced me to think about data flow vs execution flow.
- like other rustaceans, i started with a strong love-hate relationship with references, ownership and thinking about values. after some getting used-to, at least it _feels_ better to have that control over memory.
