### ISSUE TITLE
"hamid" username hardcoded in workflow

### ISSUE THREAD

**Issue by luckman212** [spamwax/alfred-pinboard-rs#21]
First: great workflow! Thanks for making this.

Little bug: when using the `alt` modifier to Reveal the bookmark on the pinboard.in website, the constructed URL is incorrect since it hardcodes `/u:hamid/?query=...`

Better would be to grab the username somewhere when user sets the API key, or if that's not possible, then require the user to set it via a workflow environment variable e.g.

![image](https://user-images.githubusercontent.com/1992842/47967715-73293d00-e02e-11e8-9d02-037bc304fef0.png)

and then

![image](https://user-images.githubusercontent.com/1992842/47967786-4de8fe80-e02f-11e8-99e8-b6ef671e0bcb.png)

**Comment by spamwax** [comment]
ugh... thanks for reporting.
I'll fix it using one of the suggested methods and push an update soon.

**Comment by luckman212** [comment]
I thought the same thing, but after refreshing my authorization token and closing and reopening the window, the username did eventually update.

**Comment by spamwax** [comment]
@matthauger did what luckman212 provide resolve your issue?
