### ISSUE TITLE
Firefox and Large Text

### ISSUE THREAD

**Issue by fncll** [spamwax/alfred-pinboard-rs#25]
I saw [Issue 8](https://github.com/spamwax/alfred-pinboard-rs/issues/8) about Firefox and invoking Large Text with Tag Suggestions on. The answer and README note imply that this should be OK with tag suggestions turned off. However, that is not my experience: I have the same issue of large text being invoked despite turning tag suggestions off. Is there any way to use this workflow with Firefox?

**Comment by spamwax** [comment]
Thanks for reporting, you are right Firefox support is broken at least for posting a pin. Will try to fix this soon.

**Comment by fncll** [comment]
Thanks in advance! As it stands, it clobbers anything in Alfred that starts with a 'p' -- took me a while to figure out what was going on :)
