### ISSUE TITLE
Can you edit tags?

### ISSUE THREAD

**Issue by jeremycherfas** [spamwax/alfred-pinboard-rs#26]
That's it. Is it possible to edit a tag within Alfred?

**Comment by spamwax** [comment]
- Pinboard API lets me rename a tag (which will affect all bookmarks using it). This is not available through this workflow though.
- If you want to change the tags of a specific bookmark, the only way to do it is to re-bookmark it with new tags.

**Comment by jeremycherfas** [comment]
OK, thanks. I was hoping for a way to tidy up my tags that have only a single bookmark. Doing it by hand will be fine.
