### ISSUE TITLE
Vivaldi Snapshot Support

### ISSUE THREAD

**Issue by r3volution11** [spamwax/alfred-pinboard-rs#28]
Title says it all. It'd be great if you can add in support for Vivaldi Snaphot.

I tried editing the applescript myself it but no luck. macOS won't ask to give permission to Alfred for access.

Snapshot does use the same bundle ID as regular Vivaldi so maybe that's the issue.

Thanks!

**Comment by spamwax** [comment]
I can't reproduce this, I installed the latest snapshot from [their blog](https://vivaldi.com/blog/snapshots/control-tab-stacks-even-more-and-sync-bookmarks-bar-vivaldi-browser-snapshot-1462-4/), and posting bookmarks of the active tab worked.

**Comment by r3volution11** [comment]
Oh okay. Thanks for checking it out. 

It must be something on my end then. I'm still guessing it deals with Alfred not having access to Vivaldi. I'm not sure how to do that manually. Time for some fun!

**Comment by r3volution11** [comment]
For anyone that may stop by:

First I reset Apple Events/Automation authorization (thanks to https://bitsplitting.org/2018/07/11/reauthorizing-automation-in-mojave/). That didn't quite fix the issue.

In a last ditch effort, I decided to throw away the regular version of Vivaldi. I then renamed Vivaldi Snapshot to just Vivaldi. It now works. Talk about a weird issue.

**Comment by spamwax** [comment]
That's probably mine worked, as I installed two version of Vivaldi in separate locations:
![screen shot 2019-02-22 at 8 32 19 pm](https://user-images.githubusercontent.com/1251233/53279738-0cb15300-36e1-11e9-9b56-cac11a229b14.png)
