### ISSUE TITLE
Append tags to previously saved bookmark

### ISSUE THREAD

**Issue by bradbarrish** [spamwax/alfred-pinboard-rs#29]
Sometimes I run across a bookmark that was previously saved, but I don't seem to be able to append any tags to it. Is that as designed? Is it possible to save with updated tags?

**Comment by spamwax** [comment]
if you bookmark again, the tags you use will replace the old ones. Pinboard API doesn't let me append tags.
you can see the current tags you have by holding down the command key before re-bookamarking.
