### ISSUE TITLE
Backslash was added automatically at the end of the last tag

### ISSUE THREAD

**Issue by amree** [spamwax/alfred-pinboard-rs#3]
Hi

Thanks for this awesome workflow but I'm having a problem with the saved tag (as per title). Steps to reproduce:

* Open a website
* Open Alfred and type: `p github issue;`
* I can see the bookmark, but `issue` tag will be saved with a backslash. Refer to the screenshot for an example

<img width="301" alt="screen shot 2018-04-14 at 8 15 09 pm" src="https://user-images.githubusercontent.com/424392/38768074-9584d994-4020-11e8-8537-bf4040e96d88.png">

Workflow version: v0.11.0

**Comment by spamwax** [comment]
semi-colon is used to provide optional notes for bookmarks.
if you are adding notes, you can just do:
`p github issue`

I will push a fix for this corner case later.
