### ISSUE TITLE
Modifier to copy URL to clipboard

### ISSUE THREAD

**Issue by matthauger** [spamwax/alfred-pinboard-rs#32]
I really like the feature that lets me hold down Alt to jump to the bookmark on pinboard.in. A related feature request? I'd love to be able to hold down a modifier that would copy the URL to the clipboard (directly from Alfred), instead of opening it on the web.

**Comment by spamwax** [comment]
right now all of modifiers are being used for other operations. I need to see if Alfred can understand modifier combos

**Comment by spamwax** [comment]
This is added in latest release. Hold down Cmd + Option to copy url to clipboard.

**Comment by matthauger** [comment]
Awesome; thanks for implementing this!
