### ISSUE TITLE
If I have shared-by-default set, option should mark as private

### ISSUE THREAD

**Issue by lilyball** [spamwax/alfred-pinboard-rs#38]
I enabled Shared Bookmarking, but it looks like holding option still posts as shared. This suggests to me that there's no way to post a private bookmark without temporarily changing the global setting first.

I haven't actually tested posting this way yet, but the subtitle still says SHARED and the repo README says it'll post as shared.

**Comment by spamwax** [comment]
Thanks for reporting. I'll try to address this when I get some free time.

**Comment by lilyball** [comment]
I see the new behavior is to just have the subtitle talk about toggling, but since the input is a script filter, why not have it override this to explicitly state whether it will enable or disable it, so I don't have to remember the current setting? Script filters can define the subtitle using [`subtitle_mod`](https://docs.rs/alfred/4.0.2/alfred/struct.ItemBuilder.html#method.subtitle_mod).

**Comment by spamwax** [comment]
good point. I was using Script filter's connection option where a subtitle can be set based on modifiers.
On the same note, in your crate, does it make sense to support changing subtitles when multiple modifiers are pressed? This can be done in Workflow's setting right now but the text will be static.

**Comment by lilyball** [comment]
I'm not aware of any way in the JSON or XML formats to declare a subtitle for a combination of modifiers. Unfortunately the documentation isn't rigorous but all the examples show a single modifier, so if there's a way to combine them it's completely undocumented.
