### ISSUE TITLE
No response  when setting token for the first time

### ISSUE THREAD

**Issue by dofine** [spamwax/alfred-pinboard-rs#43]
Edit: Alfred v 4.0.6.

Type `pa myusername:XXXX`, no reponse.
Open terminal and cd to the plugin dir,  run `./alfred-pinboard-rs config -a myusername:XXXX`, get error 
```
[2019-12-05T15:04:59Z ERROR alfred_pinboard_rs::commands::config] Couldn't save config file: ErrorMessage { msg: "missing env variable for data dir. forgot to set workflow bundle id?" 
```

**Comment by spamwax** [comment]
please enable the debug feature in Workflow's window and then run then `pa` command and then post the output here

**Comment by dofine** [comment]
> please enable the debug feature in Workflow's window and then run then `pa` command and then post the output here

Hi, it works now. Maybe network problem. Thanks!
