### ISSUE TITLE
Only post notifications is there is an error

### ISSUE THREAD

**Issue by vmlrodrigues** [spamwax/alfred-pinboard-rs#45]
Consider only posting notifications, e.g. after adding bookmark or refreshing caching, if the operation resulted in a error. Makes for few distractions.

**Comment by spamwax** [comment]
This can be easily adjusted in Alfred's Workflow window. Given that notification preferences can vary widely between users, I'll leave it to individuals to change it.

**Comment by vmlrodrigues** [comment]
Won't an update to the workflow overwrite customisations?

**Comment by vmlrodrigues** [comment]
I love the workflow btw.

**Comment by spamwax** [comment]
It will, as I mentioned introducing such a change will most likely draw complain from other users. 
In order to make your suggestion work, I should add new toggleable preferences into the code itself, which will require some time/effort.
