### ISSUE TITLE
appIsRunning applescript function no longer working in Catalina

### ISSUE THREAD

**Issue by waynehoover** [spamwax/alfred-pinboard-rs#47]
I'm on OS 10.15.3 and I was getting `'Error: osascript error: code exit code: 1` errors when trying to post urls.

I tracked down the issue to the `appIsRunning` function call in `get-current-url.applescript`. I removed [that conditional](https://github.com/spamwax/alfred-pinboard-rs/blob/master/res/workflow/get-current-url.applescript#L56) for my browser and it works again.

I suspect this is an issue with oascript permissions that has been effecting a lot of Catalina users lately. We need to find the correct permissions to grant or just remove that conditional.

**Comment by spamwax** [comment]
Thanks for the feedback. I'll look into this and push a new update. Need to remember why that condition check was there :)

**Comment by spamwax** [comment]
can you elaborate if you moved that function entirely or just from those browsers.
I am not running Catalina so testing it would be impossible for me

**Comment by waynehoover** [comment]
Enabling Full Disk Access for "System Events" in System Preferences -> Privacy -> Full Disk Access then restart seems to fix the issue.

**Comment by spamwax** [comment]
can you disable that option and try the latest release I pushed recently and see if you get any errors?

**Comment by waynehoover** [comment]
Yep, the new version also works with `System Events` disabled in `Full Disk Access`. So either way good to go. Thanks!

**Comment by eproxus** [comment]
I seem to have this problem with workflow version 0.15.12 on macOS 10.15.5. I don't see _System Events_ in the _Full Disk Access_ permissions list either.

**Comment by spamwax** [comment]
are you get the same exact error message?
I do not have access to Catalina so I can't help with permission list issue.

**Comment by eproxus** [comment]
Strangely enough, trying it today after the 10.15.5 Supplemental Update I no longer have the issue. Will keep an eye out for it, but please ignore for now. 😄
