### ISSUE TITLE
Add a note with contents of clipboard

### ISSUE THREAD

**Issue by adamkiss** [spamwax/alfred-pinboard-rs#5]
Hi,

thank you for great workflow — works very well, is fast and everything ❤️ 

I'd like to be able to add notes as well. What I imagine is very close to posting new pin, only except pulling the URL of frontmost browser, it would paste clipboard contents.

So, in alfred you'd do

```
pn @tag, @tag2; Note title
```

And it would create a note with tags and title in the background.

Thank you for considering this.

**Comment by spamwax** [comment]
Unfortunately it seems Pinboard doesn't support adding notes remotely using its API. If you know a way of doing it let me know.

**Comment by adamkiss** [comment]
@spamwax Right, I never noticed that! I contacted Maciej to find out about it, thanks.
