### ISSUE TITLE
pind is not working with firefox

### ISSUE THREAD

**Issue by sdaza** [spamwax/alfred-pinboard-rs#8]
I am just getting large letters for pind. 

I am following the recommeded path: 

- ps mybookmark
- pind

I am using Firefox 60.0.1 64-bit.

**Comment by spamwax** [comment]
Thanks for reporting. As mentioned in [readme](https://github.com/spamwax/alfred-pinboard-rs#known-issues) file, interfacing with Firefox is basically kind of a hack. I use `Command-L` to get to its address bar, which is the shortcut key in Alfred for showing large toast. 

At the moment I am not sure if this can be fixed, however I give it a try and see I can come up with another hacky way of talking to Firefox
